dist: xenial

language: java

branches:
  only:
    - develop
    - master
    - /^release\/.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - feature/improve-ci

jdk:
  - openjdk8

install: true

script:
  - ./build.sh
