dist: trusty

language: java

branches:
  only:
    - develop
    - master
    - /^release\/.*$/

jdk:
  - oraclejdk8

install: true

env:
   global:
     - DEPLOY_SOURCE_DIR=$TRAVIS_BUILD_DIR/site/build/libs

before_script:
  - chmod +x build.sh
  - chmod +x deploy.sh

script:
  - ./build.sh && ./deploy.sh

cache:
  directories:
    - $HOME/.m2
    - node
    - node_modules    
