dist: trusty

language: java

branches:
  only:
    - develop
    - master
    - /^release-.*$/

jdk:
  - oraclejdk8

install: true

before_script:
  - mvn versions:set -DnewVersion='${project.version}'-$([ $TRAVIS_PULL_REQUEST == false ] && echo ${TRAVIS_COMMIT:0:8} || echo "PR"${TRAVIS_PULL_REQUEST})

env:
   global:
     - DEPLOY_SOURCE_DIR=$TRAVIS_BUILD_DIR/site/target

script:
  - MAVEN_OPTS='-Xmx2048m' mvn -Plibrary verify

cache:
  directories:
    - $HOME/.m2
