os: linux
arch: arm64
dist: xenial

language: java

branches:
  only:
    - develop
    - master
    - /^release\/.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jdk:
  - openjdk8

install: true

script:
  - ./build.sh
